name: Inject JSON-LD into Contact HTML

on:
  push:
    branches:
      - main

permissions:
  contents: write   # Grant write permission to the repository contents

jobs:
  inject-json-ld:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # Fetch all history
          fetch-tags: true     # Fetch all tags

      # Step 2: Check if contact.html exists
      - name: Check for contact.html
        id: check_contact
        run: |
          if [ ! -f contact.html ]; then
            echo "contact.html not found, skipping workflow."
            echo "found_file=false" >> $GITHUB_ENV
          else
            echo "contact.html exists."
            echo "found_file=true" >> $GITHUB_ENV
          fi

      # Step 3: Inject JSON-LD into contact.html
      - name: Inject JSON-LD
        if: env.found_file == 'true'
        run: |
          # Verify that the JSON-LD file exists
          if [ ! -f json-ld/contact.json ]; then
            echo "json-ld/contact.json not found, skipping injection."
            exit 1
          fi

          # Read the JSON-LD content
          JSON_LD=$(cat json-ld/contact.json)

          # Use perl to perform the substitution
          perl -0777 -i.bak -pe \
            "s|<script type=\"application/ld\\+json\" src=\"contact\\.json\"></script>|<script type=\"application/ld+json\">${JSON_LD}</script>|s" \
            contact.html

          echo "Injected JSON-LD into contact.html:"
          cat contact.html

      # Step 4: Commit and push changes
      - name: Commit and push changes
        if: env.found_file == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add contact.html
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Inject JSON-LD from json-ld/contact.json into contact.html"
            git push
          fi
