name: Inject JSON-LD into Contact HTML

on:
  push:
    branches:
      - main

jobs:
  inject-json-ld:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # Fetch all history
          fetch-tags: true     # Fetch all tags

      # Step 2: Verify Git Remotes (Optional for debugging)
      - name: Verify Git Remotes
        run: git remote -v

      # Step 3: Check if contact.html exists
      - name: Check for contact.html
        id: check_contact
        run: |
          if [ ! -f contact.html ]; then
            echo "contact.html not found, skipping workflow."
            echo "found_file=false" >> $GITHUB_ENV
          else
            echo "contact.html exists."
            echo "found_file=true" >> $GITHUB_ENV

      # Step 4: Fetch and replace JSON-LD only if contact.html exists
      - name: Inject JSON-LD
        if: env.found_file == 'true'
        run: |
          # Fetch contact.json from the Utilities branch
          if git show origin/Utilities:contact.json > contact.json; then
            echo "Fetched contact.json successfully."

            # Replace the script tag in contact.html with the JSON-LD content
            JSON_LD=$(cat contact.json)
            sed -i.bak \
                "s|<script type=\"application/ld+json\" src=\"contact.json\"></script>|<script type=\"application/ld+json\">${JSON_LD}</script>|" \
                contact.html

            echo "Injected JSON-LD into contact.html."
          else
            echo "contact.json not found in Utilities branch, skipping injection."
          fi

      # Step 5: Commit and push changes only if contact.html was updated
      - name: Commit and push changes
        if: env.found_file == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add contact.html || echo "No changes to commit."
          git commit -m "Inject JSON-LD from Utilities/contact.json into contact.html" || echo "No changes to commit."
          git push || echo "Nothing to push."
